# Data Cleaning

` Data cleaning is a time consuming and unenjoyable task, yet it's a very important one. Keep in mind, "garbage in, garbage out".`

#### Feeding dirty data into a model will give us results that are meaningless.

### Objective:

1. Getting the data 
2. Cleaning the data 
3. Organizing the data - organize the cleaned data into a way that is easy to input into other algorithms

### Output :
#### cleaned and organized data in two standard text formats:

1. Corpus - a collection of text
2. Document-Term Matrix - word counts in matrix format

## Problem Statement

Look at transcripts of various comedians and note their similarities and differences and find if the stand up comedian of your choice has comedy style different than other comedian.

## Getting The Data

You can get the transcripts of some comedian from [Scraps From The Loft](http://scrapsfromtheloft.com). 

You can take help of IMDB and select only 10 or 20 comedian having highest rating.






### For example:

In [3]:
# Web scraping, pickle imports
import requests
from bs4 import BeautifulSoup
import pickle
import lxml 

# Scrapes transcript data from scrapsfromtheloft.com
def url_to_transcript(url):
    '''Returns transcript data specifically from scrapsfromtheloft.com.'''
    page = requests.get(url).text
    soup = BeautifulSoup(page, "lxml")
    text = [p.text for p in soup]
    print(url)
    return text

# URLs of transcripts in scope
urls = ['http://scrapsfromtheloft.com/2017/05/06/louis-ck-oh-my-god-full-transcript/',
        'http://scrapsfromtheloft.com/2017/04/11/dave-chappelle-age-spin-2017-full-transcript/',
        'http://scrapsfromtheloft.com/2018/03/15/ricky-gervais-humanity-transcript/',
        'http://scrapsfromtheloft.com/2017/08/07/bo-burnham-2013-full-transcript/',
        'http://scrapsfromtheloft.com/2017/05/24/bill-burr-im-sorry-feel-way-2014-full-transcript/',
        'http://scrapsfromtheloft.com/2017/04/21/jim-jefferies-bare-2014-full-transcript/',
        'http://scrapsfromtheloft.com/2017/08/02/john-mulaney-comeback-kid-2015-full-transcript/',
        'http://scrapsfromtheloft.com/2017/10/21/hasan-minhaj-homecoming-king-2017-full-transcript/',
        'http://scrapsfromtheloft.com/2017/09/19/ali-wong-baby-cobra-2016-full-transcript/',
        'http://scrapsfromtheloft.com/2017/08/03/anthony-jeselnik-thoughts-prayers-2015-full-transcript/',
        'http://scrapsfromtheloft.com/2018/03/03/mike-birbiglia-my-girlfriends-boyfriend-2013-full-transcript/',
        'http://scrapsfromtheloft.com/2017/08/19/joe-rogan-triggered-2016-full-transcript/', 
        'http://scrapsfromtheloft.com/comedy/jamie-foxx-what-had-happened-was-transcript/', 
        'http://scrapsfromtheloft.com/comedy/seth-meyers-dad-man-walking-transcript/', 
        'http://scrapsfromtheloft.com/comedy/sal-vulcano-terrified-transcript/', 
        'http://scrapsfromtheloft.com/comedy/adam-sandler-love-you-transcript/', 
        'http://scrapsfromtheloft.com/comedy/kelsey-cook-the-hustler-transcript/', 
        'http://scrapsfromtheloft.com/comedy/dylan-moran-yeah-yeah-2011-transcript/', 
        'http://scrapsfromtheloft.com/comedy/ramy-youssef-more-feelings-transcript/', 
        'http://scrapsfromtheloft.com/comedy/kevin-james-irregardless-transcript/', 
        ]

# Comedian names
comedians = ['louis', 'dave', 'ricky', 'bo', 'bill', 'jim', 'john', 'hasan', 'ali', 'anthony', 'mike', 'joe', 'jamie', 'seth', 'sal', 'adam', 'kelsey', 'dylan', 'ramy', 'kevin']

In [4]:
# # Actually request transcripts (takes a few minutes to run)
transcripts = [url_to_transcript(u) for u in urls]

http://scrapsfromtheloft.com/2017/05/06/louis-ck-oh-my-god-full-transcript/
http://scrapsfromtheloft.com/2017/04/11/dave-chappelle-age-spin-2017-full-transcript/
http://scrapsfromtheloft.com/2018/03/15/ricky-gervais-humanity-transcript/
http://scrapsfromtheloft.com/2017/08/07/bo-burnham-2013-full-transcript/
http://scrapsfromtheloft.com/2017/05/24/bill-burr-im-sorry-feel-way-2014-full-transcript/
http://scrapsfromtheloft.com/2017/04/21/jim-jefferies-bare-2014-full-transcript/
http://scrapsfromtheloft.com/2017/08/02/john-mulaney-comeback-kid-2015-full-transcript/
http://scrapsfromtheloft.com/2017/10/21/hasan-minhaj-homecoming-king-2017-full-transcript/
http://scrapsfromtheloft.com/2017/09/19/ali-wong-baby-cobra-2016-full-transcript/
http://scrapsfromtheloft.com/2017/08/03/anthony-jeselnik-thoughts-prayers-2015-full-transcript/
http://scrapsfromtheloft.com/2018/03/03/mike-birbiglia-my-girlfriends-boyfriend-2013-full-transcript/
http://scrapsfromtheloft.com/2017/08/19/joe-rogan-triggered-2016-full-transcript/
http://scrapsfromtheloft.com/comedy/jamie-foxx-what-had-happened-was-transcript/
http://scrapsfromtheloft.com/comedy/seth-meyers-dad-man-walking-transcript/
http://scrapsfromtheloft.com/comedy/sal-vulcano-terrified-transcript/
http://scrapsfromtheloft.com/comedy/adam-sandler-love-you-transcript/
http://scrapsfromtheloft.com/comedy/kelsey-cook-the-hustler-transcript/
http://scrapsfromtheloft.com/comedy/dylan-moran-yeah-yeah-2011-transcript/
http://scrapsfromtheloft.com/comedy/ramy-youssef-more-feelings-transcript/
http://scrapsfromtheloft.com/comedy/kevin-james-irregardless-transcript/

In [5]:
# # Pickle files for later use

# # Make a new directory to hold the text files
!mkdir transcripts

for i, c in enumerate(comedians):
     with open("transcripts/" + c + ".txt", "wb") as file:
        pickle.dump(transcripts[i], file)

A subdirectory or file transcripts already exists.

In [6]:
# Load pickled files
# “Pickling” is the process whereby a Python object hierarchy is converted into a byte stream, and “unpickling” is the inverse operation, whereby a byte stream (from a binary file or bytes-like object) is converted back into an object hierarchy.
data = {}
for i, c in enumerate(comedians):
    with open("transcripts/" + c + ".txt", "rb") as file:
        data[c] = pickle.load(file)

In [7]:
# Double check to make sure data has been loaded properly
data.keys()

dict_keys(['louis', 'dave', 'ricky', 'bo', 'bill', 'jim', 'john', 'hasan', 'ali', 'anthony', 'mike', 'joe', 'jamie', 'seth', 'sal', 'adam', 'kelsey', 'dylan', 'ramy', 'kevin'])

In [8]:
# More checks
data['louis'][:2]

['',

## Cleaning The Data

When dealing with numerical data, data cleaning often involves removing null values and duplicate data, dealing with outliers, etc. With text data, there are some common data cleaning techniques, which are also known as text pre-processing techniques.

With text data, this cleaning process can go on forever. There's always an exception to every cleaning step. So, we're going to follow the MVP (minimum viable product) approach - start simple and iterate.
### Assignment:
1. Perform the following data cleaning on transcripts:
i) Make text all lower case
ii) Remove punctuation
iii) Remove numerical values
iv) Remove common non-sensical text (/n)
v) Tokenize text
vi) Remove stop words

In [9]:
# Let's take a look at our data again
next(iter(data.keys()))

'louis'

In [10]:
# Notice that our dictionary is currently in key: comedian, value: list of text format
next(iter(data.values()))

['',

In [11]:
# We are going to change this to key: comedian, value: string format
def combine_text(list_of_text):
    '''Takes a list of text and combines them into one large chunk of text.'''
    combined_text = ' '.join(list_of_text)
    return combined_text

In [12]:
# Combine it!
data_combined = {key: [combine_text(value)] for (key, value) in data.items()}

In [13]:
# We can either keep it in dictionary format or put it into a pandas dataframe
import pandas as pd
pd.set_option('max_colwidth',150)

data_df = pd.DataFrame.from_dict(data_combined).transpose()
data_df.columns = ['transcript']
data_df = data_df.sort_index()
data_df

                                                                                                                                                    transcript
adam      \n\n\n\n\n\n\n\nAdam Sandler: Love You (2024) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
ali       \n\n\n\n\n\n\n\nAli Wong: Baby Cobra (2016) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
anthony   \n\n\n\n\n\n\n\nAnthony Jeselnik: Thoughts And Prayers (2015) - Full Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
bill      \n\n\n\n\n\n\n\nBILL BURR: I'M SORRY YOU FEEL THAT WAY (2014) - Full Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
bo        \n\n\n\n\n\n\n\nScraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
dave      \n\n\n\n\n\n\n\nDave Chappelle: The Age of Spin (2017) - Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
dylan     \n\n\n\n\n\n\n\nDylan Moran: Yeah, Yeah (2011) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
hasan     \n\n\n\n\n\n\n\nScraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
jamie     \n\n\n\n\n\n\n\nJamie Foxx: What Had Happened Was... (2024) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
jim       \n\n\n\n\n\n\n\nJIM JEFFERIES: BARE (2014) - Full Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
joe       \n\n\n\n\n\n\n\nJoe Rogan: Triggered (2016) - Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
john      \n\n\n\n\n\n\n\nJohn Mulaney: The Comeback Kid (2015) - Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
kelsey    \n\n\n\n\n\n\n\nKelsey Cook: The Hustler (2023) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
kevin     \n\n\n\n\n\n\n\nKevin James: Irregardless (2024) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
louis     \n\n\n\n\n\n\n\nLouis C.K.: Oh My God (2013) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
mike      \n\n\n\n\n\n\n\nMike Birbiglia: My Girlfriend's Boyfriend (2013) - Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
ramy      \n\n\n\n\n\n\n\nRamy Youssef: More Feelings (2024) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
ricky     \n\n\n\n\n\n\n\nRicky Gervais: Humanity (2018) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
sal       \n\n\n\n\n\n\n\nSal Vulcano: Terrified (2024) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
seth      \n\n\n\n\n\n\n\nSeth Meyers: Dad Man Walking (2024) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...

In [14]:
# Let's take a look at the transcript for Ali Wong
data_df.transcript.loc['ali']

" \n\n\n\n\n\n\n\nAli Wong: Baby Cobra (2016) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t\tSkip to content\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\t\t\t\t\t\tSearch\t\t\t\t\t\n \n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nMOVIES\n\nMOVIE REVIEWS\nMOVIE TRANSCRIPTS\n\n\nTV SERIES\n\nTV SHOW TRANSCRIPTS\n\n\nCOMEDY\n\nSTAND-UP COMEDY TRANSCRIPTS\nGEORGE CARLIN\nDAVE CHAPPELLE\n\n\nINTERVIEWS\n\nPLAYBOY INTERVIEWS\n\n\nMUSIC\nHISTORY\nBOOKS\nOPINIONS\n \n\n \n\nMOVIES\n\nMOVIE REVIEWS\nMOVIE TRANSCRIPTS\n\n\nTV SERIES\n\nTV SHOW TRANSCRIPTS\n\n\nCOMEDY\n\nSTAND-UP COMEDY TRANSCRIPTS\nGEORGE CARLIN\nDAVE CHAPPELLE\n\n\nINTERVIEWS\n\nPLAYBOY INTERVIEWS\n\n\nMUSIC\nHISTORY\nBOOKS\nOPINIONS\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nCOMEDY \n\n\n\n\n\n\n\nAli Wong: Baby Cobra (2016) | Transcript \n\n\n\n\n\n\n\nSeptember 19, 2017 \n\n\n\n\n\n\n\n\t\t\t\t\tAli Wong's stand up special delves into her sexual adventures, hoarding, the rocky road to pregnancy, and why feminism is terrible\t\t\t\t\n\n\n\n \n\n\n\nLadies and gentlemen, please welcome to the stage: Ali Wong!\nHi. Hello! Welcome! Thank you! Thank you for coming. Hello! Hello. We are gonna have to get this shit over with, ’cause I have to pee in, like, ten minutes. But thank you, everybody, so much for coming.\nUm… It’s a very exciting day for me. It’s been a very exciting year for me. I turned 33 this year. Yes! Thank you, five people. I appreciate that. Uh, I can tell that I’m getting older, because, now, when I see an 18-year-old girl, my automatic thought… is “Fuck you.” “Fuck you. I don’t even know you, but fuck you!” ‘Cause I’m straight up jealous. I’m jealous, first and foremost, of their metabolism. Because 18-year-old girls, they could just eat like shit, and then they take a shit and have a six-pack, right? They got that-that beautiful inner thigh clearance where they put their feet together and there’s that huge gap here with the light of potential just radiating through.\nAnd then, when they go to sleep, they just go to sleep. Right? They don’t have insomnia yet. They don’t know what it’s like to have to take a Ambien or download a Meditation Oasis podcast to calm the chatter of regret and resentment towards your family just cluttering your mind. They have their whole lives ahead of them. They don’t have HPV yet. They just go to sleep in peace at night. Everybody has HPV, OK? Everybody has it. It’s OK. Come out already. Everybody has it. If you don’t have it yet, you go and get it. You go and get it. It’s coming. You don’t have HPV yet, you’re a fucking loser, all right? That’s what that says about you. A lot of men don’t know that they have HPV, because it’s undetectable in men. It’s really fucked up. HPV is a ghost that lives inside men’s bodies and says, “Boo!” in women’s bodies. My doctor told me that I have one of two strains of HPV. Either I have the kind that’s gonna turn into cervical cancer… …or I have the kind where my body will heal itself. Very helpful, this doctor, right? So, basically, either I’m gonna die… or you’re in the presence of Wolverine, bitches. We’ll find out.\nUm, I can also tell that I’m getting older, because my Kindle is turning into a self-help library. I’m not interested in books like Fifty Shades of Grey, OK? I’m interested in The Life-Changing Magic of Tidying Up. Yes. Yes, that’s right, how to declutter my home to achieve inner peace and my optimum level of success. That’s what your 30s is all about. How can I turn this shit around? I’m a horrible person, I’m not happy with where I am, how can I turn this shit around? Help me, Tony Robbins, help me!\nI have a hoarding problem, which I’m hoping is the center of all of my other problems. I’m hoping that if the hoarding goes away, the HPV will also disappear. I have a hoarding problem because my mom is from a third world country and she taught me that you can never throw away anything, because you never know when a dictator’s gonna overtake the country and snatch all your wealth. So, you better hold onto that retainer from the third grade, ’cause it might come in handy as a shovel when you’re busy stuffing gold up your butt and running away from the Communists.\nThe last time I was at home in San Francisco, I was trying to help her get rid of shit. Don’t ever do that with your mom. It was like the worst experience of my life. It was so emotional. We were screaming and fighting and yelling and it all came to a climax when she refused to let go of a Texas Instruments TI-82… manual. The manual. She don’t even know… where the calculator is. Those of you under 25 probably don’t know what that calculator is. It was this calculator that bamboozled my generation. We were all required to buy it when we were in eight grade. It cost like $200. And everybody thought it was like this Judy Jetson’s laptop from the future. All because what? It could graph. It was like the Tesla of my time. And my mom got so emotional about the manual and she was like, “You never know when you might need this.” And I was like, “But… I do know… that I’m gonna have to clean all this shit up when you die.” “And I’m not trying to be a procrastinator anymore. Because according to Deepak-Oprah, that’s not the way for me to achieve my optimum level of success.”\nI grew up a lot this past year. Uh, this past year I also got married. Yeah. To a man who now has HPV. Very lucky guy. He gave me something. I gave him something. That will also last forever. No, really. I’m the lucky girl, because before him, I dated a lot of losers. Lots of losers. A lot of skaters. You wanna be a grown-ass woman, stop dating skaters. Stop dating skaters unless you wanna wake up on a mattress in a kitchen. They’re sexy on the outside, malt liquor on the inside. Horrible. But my husband, I first met him at this wedding and, uh, he’s– he’s much better looking than me, he’s way out of my league, and I saw him and I was like, “Oh, my God, who is that?” And the first thing I learned about him was that, at the time, he was attending Harvard Business School. And I was like, “Oh, my God, I’m gonna trap his ass.” “Going to trap his ass!” And I trapped his ass initially by not kissing him until the fifth date, which is a very unusual move on my part. But I did it on purpose, because I knew that he was a catch. So I was like, “All right, Ali, you gotta make this dude believe that your body is a secret garden.” When, really, it’s a public park… …that has hosted many reggae fests… …and has even accidentally let… two homeless people inside. I thought they were hipsters, OK? That store Urban Outfitters has made things very confusing… for my generation. You homeless or you a hipster? Is that beard for fashion or for warmth? It happened to… It happened in San Francisco, when I was living there, and I saw this guy in broad daylight and we had, like, we had… We had so much chemistry. He was like, “Hey, wassup?” I was like, “Wassup?” And we– The next thing I knew, we were getting busy in the back of my Volvo. And then after we were done, he was like, “Hey, can you drop me off?” I was like, “Where?” He was like, “At the park.” And I dropped him off at Golden Gate Park and watched him run into the middle with all his other homeless friends, and I was like, “Oh, no!” “I just fucked a homeless dude! Again!”\nMy husband is Asian. Which a lot of people are shocked by, because, usually, Asian-American women who, like, you know, wear these kinda glasses and have a lot of opinions, they like to date white dudes. You go to any hipster neighborhood in a major city in America and that shit is turning into a Yoko Ono factory. It’s… too much. I don’t know what’s wrong with these bitches. I get it, you know, because being with a white dude you feel very… You feel very picturesque when you’re with a white dude, you know. You feel like you’re in a Wes Anderson movie or something. And you know, white dudes, they teach you about a lot of cool stuff like voting and recycling, and disturbing documentaries. They introduce you to cool stuff like that and it’s very, you know, it’s hot hookin’ up with a white dude. I mean, nothing makes me feel more powerful than when a white dude eats my pussy. Oh, my God. I just feel like I’m absorbing all of that privilege and all of that entitlement… …you know, just right there, through the money hole and just… And then also, he’s so vulnerable down there. I’m, like, “I could just crush your head at any moment, white man! I could just kill you right now! Crush those brains! Colonize the colonizer!” You know?\nBut I think that for marriage, it can be nice to be with somebody of your own race. The advantage is that you get to go home… and be racist together. You get to say whatever you like! You don’t gotta explain shit. My husband, half-Filipino, half-Japanese. I’m half-Chinese and half-Vietnamese. And we spend 100 percent of our time shitting on Korean people. It’s… amazing. It’s what love is built on, you know?\nMy last boyfriend was Cuban and his family would shit on Mexican people all the time. And I was like, “Hold it. You guys aren’t Mexican?” Asian-American men are very underrated. I don’t know why people don’t go for them. They’re the sexiest. Asian men are the sexiest. They got no body hair from the neck down. It’s like making love to a dolphin. Oh, my God. It’s so smooth, just like a slip and slide. Just black fish, Tilikum, all up in my bed every night, you know? Ooh-wee. You mess with a Jewish dude and your body is all fucked up afterwards. It’s all red and inflamed and you’re like, “I did not ask to be exfoliated today.” “This is the last time I go on J-date, more like loofah date. Thanks for the rug burn, Avi.” And then Asian men, no body odor. None. They just smell like responsibility. That’s where the umami flavor comes from.\nI think my husband and I have a huge unspoken understanding, uh, between each other, because he’s half-Filipino and half-Japanese and I’m half-Chinese and half-Vietnamese. So, we’re both half-fancy Asian… …and half-jungle Asian. Yeah! You guys know the difference. The fancy Asians are the Chinese, the Japanese. They get to do fancy things like host Olympics. Jungle Asians host diseases. It’s… It’s different. But he grew up on the East Coast, going to private school, playing lacrosse, uh, you know, learning Latin and playing chess and rugby. He grew up like Filipino Carlton, OK? So, he didn’t know anything about Vietnamese people until he met me. And on one of our first dates, he took me to this restaurant on the west side of Los Angeles called Pho Show. He was like, “It’s authentic Vietnamese. I read about it on Yelp!” I was like, “It’s not authentic, OK?” You can tell, first and foremost, by the name, ’cause it don’t got a number in it. Second of all, you can tell by the bathroom. If it was legit, the bathroom would double as a supply closet. When I pee, I need to see ten gallons of bleach, an ATM machine and a grandma with glaucoma napping in the corner. And the wait staff here is too nice. We need to leave this restaurant deaf and emotionally abused.\nI grew up going to private school, too. Him and I are both total, like, private school Asians. We both are big hippies, too. We like to backpack through Southeast Asia. We like to do yoga. We do ayahuasca ceremonies. We do silent meditation retreats. That’s right, we pay $800 to shut up for a weekend. We do shit like that. Uh, we eat gluten-free, which means we eat all that bread that tastes like free-range Chewbacca. We eat that lesbian bread that’s like… …a thousand percent of your daily fiber… and 20 percent spoken word poetry. When you eat it, you queef a shitty poem about… …supporting Caitlyn Jenner or whatever. And so, it’s funny, right, because he’s Asian, too. But sometimes, all of this hippy-dippy shit we do… makes me feel like we are white people doing an impression of Asian people. Like, we have these Chinese scrolls up on the wall… and neither of us know what the fuck they mean. We’re like, “Oh, that seems to go very well with our Buddha piggy bank from Pier 1 Imports. That seems to be providing some good feng shui for the house.\nHim and I had been dating for four years and I– I just had this sneaking suspicion that he was gonna propose… because… I had been pressuring him to do it. So, you know, I just had this wacky women’s intuition. That’s how proposals really work, OK? A woman has to incept the idea into the man’s head. First passively and then if he doesn’t get the message, extremely aggressively. You gotta threaten to leave without ever actually leaving, because you know that you’re too old and it’s too late to go back out there and find a new man and start the whole manipulation cycle all over again. So, you’re like, “I’m just gonna stick with this dude, focus on trapping this dude, and just nag the shit outta him until he becomes weak and caves in and gets fed up and is like, “Shut the fuck up! Fine, will you marry me?” And then afterwards, the woman is always, like, “Oh, my God! He proposed!” “It came outta nowhere. And look, he got me the exact ring I wanted. How did he know? Maybe he saw it on my Pinterest page or something… that I sent to my best friend, that I told her to send to him every day.” Let me tell you something. If a man has a Pinterest page… he’s probably Pinterested in men. We got engaged on a Saturday. I bought my wedding dress the following Tuesday… because I had tried it on in 2012. I was ready. I was ripe. I was rotten. I need to be made into banana bread. That’s how rotten I was.\nPeople are always very surprised at how, off-stage, with my husband, I’m a completely different person. You– Like, you would not recognize my personality at all with him. With him, I’m very soft, and, like, very nurturing and very domestic. We’ve been together now for five years, and for five years, I’ve packed his lunch every single day. Yeah. Yes. Yes. Yes. I did that so that he’d become dependent on me. ‘Cause he graduated from Harvard Business School, and I don’t wanna work anymore. I don’t. I straight up don’t wanna work anymore. I don’t feed him out of the goodness of my heart. I do it as an investment in my financial future. ‘Cause I don’t wanna work anymore. I’ve been reading that book by Sheryl Sandberg, she’s the C.O.O. of Facebook, and she wrote that book that got women all riled up about our careers. Talking about how we as women should challenge ourselves to sit at the table and rise to the top. And her book is called Lean In. Well, I don’t wanna lean in, OK? I wanna lie down. I want to lie the fuck down. I think feminism is the worst thing that ever happened to women. Our job used to be no job. We had it so good. We could have done the smart thing, which would have been to continue playing dumb for the next century and be like, “We’re dumb women. We don’t know how to do anything. So, I guess we better just stay at home all day and eat snacks and watch Ellen.” “‘Cause we’re too stupid to have any real responsibility.” And then, all these women had to show off and be like, “We could do it! We could do anything.” “Bitch, shut up!” “Don’t tell them the secret.” They ruined it for us, and now we’re expected to work. When I hear the phrase, “Double-income household,” I wanna throw up. A lot of women get very upset with me about those comments. And they’re like, “But, Ali, we have so many more options now.” Oh, you don’t think we had a lot of options when our day was free? Unscheduled, unsupervised, and most importantly, sponsored? Do you know how much shittier food tastes when you know you have to earn it?\nA lot of my friends, when we walk around together, they’ll get very judgmental about housewives that we’ll see on the street. And they’ll be like, “Look at that fucking housewife. Not doing anything. Look at that housewife, just walking around all day, getting massages in her Lululemon pants.” I’m like, “That bitch is a genius.” “She’s not a housewife, she’s retired.”\nI do write for Fresh Off the Boat on ABC. Yeah. Which is… It’s a great show. I love it a lot. I love my co-workers. It’s a great writing staff and in terms of day jobs, it’s probably one of the best you could ask for, but I still gotta work at a office every day. Which means I gotta shit in a office every day. Housewives, they don’t gotta shit in a office. Housewives get to shit in their house. Skin to seat. They don’t gotta use that horrible toilet paper cover. They don’t gotta… …ten times a day, every day… like you’re about to eat a sad-ass meal. They don’t gotta do that. They don’t gotta use that one-ply toilet paper, that office toilet paper, that they purposely make difficult to pull out. They try to ration me with their communist toilet paper that’s not even effective. It basically just dehydrates your butt hole. It’s basically like wiping your butt with the desert. I literally spat on my toilet paper two days ago, to try to make a MacGyver baby wipe, to moisten it, and then it backfired ’cause my fingers broke through and digitally stimulated more doo doo to come out, and then I had to start all over again. And you can never finish wiping at work because you always feel rushed ’cause you’re paranoid that your co-worker’s gonna recognize your shoes underneath the stall. And you’re like, “Oh, no! Courtney’s listening. She’s waiting. She’s timing me.” And then you hurry, hurry, hurry, and then you never finish wiping and then your butt hole feels caked in doo doo all day long. And then if you dare scratch yourself, your underwear at the end of the day looks like it’s been run over by the Goonies. Housewives, they don’t gotta muffle their shit, too. They don’t gotta worry about the velocity with which their doo doo comes out. They don’t gotta try to, you know, squeeze the butt cheeks together to make sure that the doo doo comes out at a slow and steady pace, so that no unpredictable noise suddenly escapes and brings you deep, deep shame. Housewives are free to just blow ass into the toilet and let it echo and reverberate to the ends of their hallways while watching as much Netflix on their iPad as they want. They don’t gotta take these boring, repressed shits. They can listen to podcasts. Planet Money. They can do whatever they want.\nYou know, it’s– it’s very distracting for me when I hear my co-workers blow ass into the toilet. I lose respect for them. Nothing they say to me anymore holds any sort of credence. I heard one of my co-workers blow ass into the toilet the other day. This bitch had the nerve to come up to me and say, “You need to get to work on time.” I was like, “You need to eat bananas.” “I saw those green ballet flats. I know that shit was you. Don’t try to tell me to get my shit together when I heard you not have your shit together.”\nMy father-in-law had this huge sit-down with me and my husband recently. Um, and he was like, “Hey, I wanna talk to you guys about money. You guys need to make a lot more money if you wanna provide your children with the same kind of privileged childhood that you guys had.” I was like, “Why you telling me this shit? I should not be a part of this conversation. You tell you son that. Don’t your understand that I trapped your son for his earning potential? Why else would I choose to fuck one person for the rest of my life? I chose to marry him on the promise of early retirement, and when I said, ‘I do,’ what I really meant was, ‘Oh, I’m done.'” I’m done. I don’t wanna work anymore and I’m not dieting anymore. Since I got married last year, I’ve been eating fried chicken skin every day since. That’s right. And just fulfilling my destiny. Which is to turn into a circle with eyelashes. Like Mrs. Pacman, just… Let’s redecorate.\nI gave up a lot of myself when I got married. I’m a– I’m a disgusting pervert. I’m a pervert. I’m a gross filthy animal.

In [15]:
# Apply a first round of text cleaning techniques
import re
import string

def clean_text_round1(text):
    '''Make text lowercase, remove text in square brackets, remove punctuation and remove words containing numbers.'''
    text = text.lower()
    print(text)
    text = re.sub('\[.*?\]', '', text)
    print(text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    print(text)
    text = re.sub('\w*\d\w*', '', text)
    print(text)
    return text

round1 = lambda x: clean_text_round1(x)

<>:9: SyntaxWarning: invalid escape sequence '\['
<>:13: SyntaxWarning: invalid escape sequence '\w'
<>:9: SyntaxWarning: invalid escape sequence '\['
<>:13: SyntaxWarning: invalid escape sequence '\w'
C:\Users\Mandar Garud\AppData\Local\Temp\ipykernel_6804\3147248594.py:9: SyntaxWarning: invalid escape sequence '\['
  text = re.sub('\[.*?\]', '', text)
C:\Users\Mandar Garud\AppData\Local\Temp\ipykernel_6804\3147248594.py:13: SyntaxWarning: invalid escape sequence '\w'
  text = re.sub('\w*\d\w*', '', text)

In [16]:
# Let's take a look at the updated text
data_clean = pd.DataFrame(data_df.transcript.apply(round1))
data_clean

adam sandler: love you (2024) | transcript - scraps from the loft






















































































		skip to content




















						search





















movies

movie reviews
movie transcripts


tv series

tv show transcripts


comedy

stand-up comedy transcripts
george carlin
dave chappelle


interviews

playboy interviews


music
history
books
opinions




movies

movie reviews
movie transcripts


tv series

tv show transcripts


comedy

stand-up comedy transcripts
george carlin
dave chappelle


interviews

playboy interviews


music
history
books
opinions





















comedy







adam sandler: love you (2024) | transcript







august 27, 2024







					after a rather oddly chaotic beginning -adam arrives late to the gig, driving a car with a broken windshield, the show gains momentum. two songs exemplify typical sandler humor: "bulldog in a halloween costume" and "the drone song".







[crickets and city sounds fade in]
[car approaching]
[“lotta love” by nicolette larson plays]
[fans shouting]
[man] back up! back up!
♪ it’s gonna take a lotta love ♪ ♪ to get us through the night… ♪
yo, vil, what happened? i thought you guys were fixing this shit. i’m driving in the car like this, putting my head out the window.
[adam]… spilled fuckin’ coffee.
[vil] it’ll be done, boss. sorry ’bout that. i’ll get ya after the show. i think i’m late. i think i’m late. i’ll get you guys after. what’s up? what’s up? what’s up? how are we doing on time? doing good? how’s lester doing?
[man] adam!
[crowd clamoring]
ask him… ask him now.
[adam] hey, young man. how are you? what are you doing out so late with all these crazy people? what do you got? what is this? is this me… me in my house? we got these in manhattan.
they sell photos of movie stars.
you did? you know this kid?
you’re a movie star. he’s my son!
that’s your son? when’s… when’s his birthday?
tell him when your birthday is.
no, you tell him when his birthday is. i had covid, i lost memory of that. your grandmother’s a sick woman. come on, you said you’d sign for children!
[man] this way.
don’t be mad, i gotta do the show. i’ll see you in there. i’ll see you. i’ll get it right after. so, go in here?
why didn’t they lock up the alley?
[loughran] i tried, they’re short-staffed.
[man 2] don’t want some chinese food?
[adam] what? no, i’m not eating.
[man 2] i’ll throw it out?
i gotta change my shirt.
[man] dressing rooms…
um, is this the stage?
[lester] you know the stiff neck is better than one of these deals. [shouts]
[adam] how’s he doing?
he’s doin’ good. this is a person with a stiff neck watching a pro tennis player hit an ace.
[shouts] oh!
[audience laughs]
[lester] aces don’t come back.
who booked this place?
[man] not me.
well, it’s…
[bergie] adam!
bergie, my god. this is the worst moment of my life. you’re here. how’s it going? skip. nice to meet you. i work with bergie. i’ll pay you $1,000 to murder this man right now. that’s not funny! we gotta get this stuff done.
i got goddamn coffee all over this shirt.
[ann] you want one of these shirts?
[adam] i don’t know. i need a hoodie.
want this one?
that’d be…
[skip] it’s an xl.
[adam] i don’t know if we’re in the same weight class, but alright. put this shit on. actually, just keep it off.
give him a thrill, would you?
oh stop!
would you sign this stuff?



i can’t do it now. we got 40 pieces to do. it’s for ms charity.
[adam] i got a show to do, bergie.
we gotta go. we’re late!
yeah, i know. bergie. bergie. bergie. i got it. give me the shit. i know, i gotta… i can’t do them all right now.
[bergie] you gotta get them done!
[loughran] we’ll get it to you.
no, it’s for ms. i gotta do this shit. let me just… there was a kid outside i was a dick to.
[bergie] does he have ms?
[adam] no. then absolutely not. this goes to ms. give him a fucking putter. thank you, buddy. come on, let’s go.
nice to meet you, adam.
thanks for the sweatshirt.
here’s your coffee.
stevia?
of course. going down the stairs.
[man] have a good set. i’m gonna play some of the synths in comedy live, if that’s cool.
[adam] yeah. sure.
“bees, maple syrup,” we cut.
[adam] oh, let me do that if i want to!
we’ll see what happens. alright.
[dan] it’s in there. jellyfish…
[dog barking]
[adam] oh!
whose dog is that?
[dan] dunno. this place is crazy.
[adam] what the fuck is going on?
[man 5] left and left.
[adam] okay, left and a left.
[dan] ‘locked door’, we have the second verse there right now.
is that cool?
[adam] yeah. it’s, uh… okay.
[dan] i think we should try a vocoder. is that cool?
[adam] yeah, yeah. that’ll be funny. so i just…
i just sing normal?
[dan] you do it totally normally.
alright.
[dan] everything you do is the same. excuse me, mr. sandler, i’m sorry to interrupt you. not at all. what’s doing? wonder if you could do me a big favor and say a few words to my son, james.
absolutely.
he’s in the hospital. let me do this show… oh, he’s in the hospital. he had a big accident on his scooter.
i’m sorry to hear that.
he really injured himself. and he’s a big fan of yours.
[adam] alright, i’ll see…
james.
[adam] he’s here?
[woman] i’ve got mr. sandler right here.
[adam] oh.
hey, james!
no way! no way!
yeah. – is that mr. sandler?
hey, man! – oh my god… you landed on your face, huh, bro? mr. sandler, i’m not feeling good.
i see that! – please come see me in the hospital. i would love to see you, man. [chuckles] i’m doing a comedy show right now. you’re going to be okay! mr. sandler, i promise i’m not gonna make it.



i’ll see ya…
[willie] adam.
definitely…
good show.
thank you.
alright, i’ll set up.
have a good show.
adam! yeah. yeah. i’m sorry. pardon me.
[willie] great audience.
you were fantastic. thank you so much.
you guys were great.
they made me feel real. willie and lester, you guys…
[loughran] ladies and gentlemen…
this means a lot to me.
[adam] the crowd loves you.
[willie] appreciate that. please give it up for mr. adam sandler!
[willie] go get ’em, adam.
let’s go.
[lester] take care! break a leg!
[music playing]
[adam] that was already insane. i don’t know what happened. ladies and gentlemen, thank you.
[cheers and applause]
thank you very much. thank you. alright. don’t do that. i love ya. alright! hi. hi! how are you? alright, guys. bulla. nice to see you all! what’s up? hi, guys!
[cheers and applause continue]
alright, i love you. thank you so much! alright, we got a whole show. alright. thanks a lot, everybody. i love you. thanks for coming out. what’s going on with the…
why is that doing that?
[dan laughs]
why’s the…
[tech] we’re working on it. a computer issue. we’re working on it. got a computer… alright. so what? you want to wait for… should i wait?
[tech] no, no let’s not wait. let’s keep going. we’re gonna get them working. it’ll be fine. let’s just go. alright. yeah, alright. okay, so, just go and we’ll do this, because we got so many things that we’re supposed to show up there.
[dan laughs] alright. it’s alright.
we’ll, we’ll…
[audience laughs] no, no, no. that’s what it’s gonna look like? i don’t know.
[tech] we’re gonna kill them. this is, uhh, splenda you put in here. you fucked me. it was supposed to be stevia.
[dan chuckles]
[tech] let’s kill the monitors, please.
just kill the monitors. yeah. just go to black.
yeah. alright.
[audience whoops]
[audience applauding]
ladies and gentlemen. what a… thank you.
[applause continues]
alright. alright. so, i was eating grapes.
[audience laughs]
i was eating some grapes. it was going good.
this guy i was with goes, “you!”
[crowd laughs]
i was like, “what, what?” he goes, “you… you’ve changed.” i said, “get out of here, i always liked grapes.” and, uh… he’s like, “i don’t like this version of you.” and i said, “fuck, i’ve been eating grapes my whole life, calm the fuck down.” he goes, “i’m leaving” i said “well, get outta here, then.” “i’ve had enough of you too.” so, anyways, he left, and then i said to the man who was feeding me the grapes, i said, “what do you think? you think i changed?” and he’s like, “no.” and i go, “he changed, right?” he goes, “yeah!” “he changed, sandman.” a woman outside said to me, “hey, i got a tattoo of you on my calf.” i was like, “alright, that looks good.” and she’s like, “yeah, i like it too.” and then her husband goes, “adam, can i talk to you?” “come here for a minute.” i go, “what’s up, dude?” he goes, “you think i like that bullshit?” “fuckin’ makin’ love to my wife? got her legs up here.” “i look over, i see your fucking ugly face?” “you think i like that bullshit?” i go, “oh, well…” “you don’t gotta look.” he goes, “how am i gonna finish, adam?” “i’ve grown accustomed to your face.” i got a letter recently from a man. i opened it up and it says, “my name is charlie mungo.” “i am one-foot tall, and i’m gonna shoot you.” i was, like, “uh-oh.”
anyways, a couple weeks goes by, i get this… another letter. open it up. “it’s me, charlie mungo.” “still one foot.” “you’re fucking dead, sandman.” i was like, “whoa. shit. this guy means business.” couple weeks goes by, same kind of scribble-scrabble on this envelope. i go, “here we go.” i open it up. it says, “fuck you.” “you don’t deserve to live, sandman.” “this is charlie mungo.” “you will pay for your sins.” [laughing] “p.s.” “still one-foot tall.” i was like “fuck, man.” my friends were like, “you gotta report that shit.” “that’s gotta go to the fbi, you know?” i said, “you know what? fuck it” “i’m not telling nobody ’cause then charlie mungo wins.” “gotta just live my life, you know?” you know what i’m saying. i did get bulletproof socks.
[audience clapping]



so, uh…
[keyboard plays softly]
um, what happened? yes, so, what is that? huh? coffee with stevia.
[clapping]
huh? sorry, it was splenda. it was splenda!
you’re good!
i’m good, man! i fucking knew it!
[piano chord plays]
well, i love you. i’m glad you were honest. mm-hmm. [smacks lips] that’s stevia, yeah. thank you, buddy. thanks for confessing.
[piano tune playing]
[angry man] why don’t you shut the fuck up with that laughing? hang on. hang on.
everything okay over here?
[woman 1] shut the fuck up!
[woman 2] they won’t be quiet.
who won’t be quiet?
[woman 3] he threatened to put him in his place.
oh, you guys, don’t worry.
[woman 2] because we’re laughing. alright. well, everyone laughs in… in their own way. [chuckles] how about you don’t look at each other the whole show. but you can fucking laugh. you guys laugh, you guys laugh. then, after the show, we’ll all get in a massive fight.
[laughter and applause]
[piano playing]
alright. don’t worry. i love you. you guys just have a good time.
♪ she’s got long brown hair tied up in a little red bonnet ♪ ♪ she’s got a pretty white blouse and a basket with fresh fruit upon it ♪ ♪ she’s got a glow in her cheeks and a fire inside ♪ ♪ sitting in a beautiful countryside ♪ ♪ oh, masturbating to the lady on the box of raisins ♪
[piano stops]
[laughter] alright. so that… [chuckles] it was supposed to be, uh… you were supposed to show her up there.
goddammit.
[applause]
[tech] we’re working on it. i think we have a… the computers are very old. just trying to figure out… nobody wanted to chip in and get a fucking new one? [laughter] i was, uh, at a restaurant recently. i was eating a hamburger, having a nice time. a guy comes up and says, “can i take a picture of your hamburger?” i said, “uh, how come?” he said, “i’m from spain.” i said, “you guys got hamburgers.” he goes, “yeah, but that’s a big juicy one.” [chuckles] so i go, “alright, take the picture, bro.” then like, 20 minutes, he’s taking a picture of another guy’s hamburger. and i go, “what’s going on, bro?” and he goes, “this one’s bigger.” and then i go, “well, fucking delete mine, then.”
i, uh… [chuckles] i took the family to the fuckin’ circus. we’re having a good time. the clown car comes out. they got 15 fucking clowns in one little tiny car. my kids were like, “holy shit. how they doin’ it?” i said, “i don’t know. they’re fucking pros.” anyway, we were driving home, the kids are still talking about it. “fucking incredible.” all of a sudden, the little car rolls up next to us on the highway. i’m like, “kids, look over there. all 15 fucking clowns are in there.” my kids are like, “yeah! great show!” they’re, like, smoking butts. like, “yeah, whassup?” you know? “it’s all good, baby. alright.” and then they hit an oil slick. and they fucking spin. i was like, “holy shit,” and it fucking kept spinning and shit. my kids are like, “what’s happening?” then they hit the guardrail. i was like, “oh no!” they’re sliding across, i hit the fucking brakes. it goes right past, it hits the truck, fuckin’ blows up. we were like, “did we just see that shit?” that was horrible. my kids are crying. i was like, “goodness gracious, this night changed.” anyways, we went to the funeral. and, uh, we get there… one coffin, all 15 of them, and i was like, “they still got it, man.” “these fucking guys still got it.” thank you so much. you guys are my best friends. thank you.
[upbeat piano tune playing]
yeah, yeah.
♪ she’s the happiest she’s been in years ♪ ♪ he puts on a big smile on her face ♪
[piano falls]
oh shit! whoa, you son of a bitch!
[audience laughs]
that’s gonna happen. that’s all fine.
it’s all part of the plan.
[dan chuckles] what happened? uh, why did that happen? it’s a fucking… there’s a hole in the ground.
alright.
there’s a hole in the stage. it’s all working out tonight. so, what do we do right now?
so we do the whole show like this?
digby… yeah.
what’s up, buddy?
[dan chuckles] thank you so much. thank you. will you see if there’s a good monitor down there too?
[piano riff]
[audience laughs] yeah, yeah, let’s… alright.
lauren.
lauren.
[audience laughs]
thank you. sorry, everybody. we’re gonna get this right. i like that chicken parm shirt. that’s funny.
[dan] we could just do…



[adam] what is that? oh, a fucking lunch tray? there’s no way that’s going to work. there’s no way… are you fucking kidding me?
[applause]
nice job. holy shit, you guys are good. this is a bad sign, everybody. okay, let’s go.
[upbeat piano tune playing]
♪ she’s the happiest she’s been in years ♪ ♪ he puts a big smile on her face ♪ ♪ he’s got a good job and me and my parents love the dude ♪ ♪ you can tell that he’s gonna be faithful ♪ ♪ the whole family is happy as hell ♪ ♪ my sister’s got an ugly new boyfriend ♪
[piano stops]
[laughter] thank you. thank you. we needed that one, guys. we needed that one. hoo!
[soft piano tune plays]
alright. alright. let’s see what we got here. hmm. let’s see how we do on this one. a little guitar. only if you encourage me with some applause. you want some guitar?
[audience cheering and applauding]
here we go!
[strumming twangy melody]
[audience whooping and clapping]
[strumming chords]
[audience cheers and applauds]
[dramatic flourish]
[cheers and applause]
[guitar melody continues]
[dramatic flourish]
[audience cheers and applauds]
[flourishes continue]
[audience continues reacting]
[audience laughs]
[audience cheers and applauds]
[flourishing guitar solo continues]
[guitar solo intensifies]
[audience cheers and applauds]
♪ every day i’m mutterin’ ♪ ♪ mutterin’ under my breath ♪
[country western tune playing]
hyah! [mimics whip cracking] [mimics horse neighing]
♪ if you ask me to do a task ♪ hyah! [mimics whip cracking] ♪ i do it every time ♪ hyah! [mimics whip cracking] ♪ but the whole time that i’m doing it ♪ [mimics horse neighing] ♪ i’ll be mutterin’ under my breath ♪ [low] how come i gotta do this fucking shit? no one else could have done it? i’m fucking sick of this crap, man. all they do is sit there all day. i do every fucking thing in this house. fuck these people. [chuckles] ♪ things i’d never say to your face ♪ hyah! [mimics whip cracking] ♪ but the second that you’re gone ♪ hyah! [mimics whip cracking] ♪ i mutter like a crazy asshole ♪ [mimics horse neighing] ♪ while i angrily mow the lawn ♪
[low] how come i’m fucking mowing this shit? goddamn this fucking house… they can’t do nothin’. fuckin’… they know how to start this fuckin’ thing. fucking bullshit, it’s always me. the fuckin’ grass just grows back. why the fuck am i out here? i can’t stand these motherfuckers.
[muttering] ♪ rake the leaves ♪ ♪ i’m mutterin’ ♪ ♪ shovel snow ♪ i’m… [laughs] ♪ i’m mutterin’ ♪ ♪ go to the bank! ♪ ♪ you know i’m mutterin’ ♪ ♪ take out the trash! ♪ ♪ there’s mutterin’ ♪ ♪ when there’s toys at the bottom of the pool ♪ ♪ left there by my daughter ♪ ♪ as i swim down to get them ♪ ♪ i’ll be mutterin’ underwater ♪ [low, bubbling] you can’t get your own fucking toys? or at least buy fucking toys that float? what the fuck has happened to my fucking life? [mimics horse neighing underwater] ♪ everyday, i’m mutterin’ ♪ hyah! [mimics whip cracking] ♪ mutterin’ under my breath ♪ [mimics horse neighing] [chuckles] ♪ then one day my wife overhears what i’m saying ♪ ♪ and immediately slits ♪ ♪ my throat ♪ [dramatic flourish]
[cheers and applause]
you guys are the fucking best! i love you! i love you! i need you! help me! so, my grandparents retired, and that was nice. and then my grandmother panicked. she’s like, “oh no, we have no income. how we gonna pay for things?” so she opened a kissing booth in our driveway. she built a little booth, put a little sign. “$20 a kiss.” every car was just whizzing past. my grandfather comes out,
gives her $20 and gave her a kiss.
[crowd awws] and then, he gave her another $20, gave her a longer kiss. then he gave her another $20. kind of a deeper, mouth-open kind of thing. went up the back of the thing, snapped the fucking bra. pulled the bra out, whipped it on the ground, got the hands rolling. the belt line, then got the hand in, went some buns. a little bun-smacking, went down the middle, finger tapping and shit. and then we were all like, “this is fucked up,” uh, because it was my other grandfather.
[audience exclaims]
yeah. [chuckles] they used to flirt, but we didn’t know… we didn’t see that coming. uh… [chuckles] um… yeah, so i, uh… my wife is younger than me.
anybody have a younger wife here?
[man shouts]
you do, right? you understand what i’m saying? my wife’s eight years younger than me. that was fine when we were young, because… now that we’re older, she still looks good, i’m starting to look a little beaten. know what i mean? and i don’t wanna… i don’t want to do plastic surgery. i’ll never do that. i did try botox… on my dick. i botoxed my dick. i wanted to make her… a freshening-up, give her a better… a younger-looking dick to slap around. i felt like… i felt bad for her. my dick was starting to get a little… a little worn-looking. you know, a little… almost like it needed a cane. it was always kind of leaning. scoliosis dick. kind of leaning on the right ball. my left ball was always like, “how the fuck do i get left out?” my right ball was like, “shh, you’re gonna wake him.” “let him rest. he’s tired.”

                                                                                                                                                    transcript
adam      \n\n\n\n\n\n\n\nadam sandler love you   transcript  scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
ali       \n\n\n\n\n\n\n\nali wong baby cobra   transcript  scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
anthony   \n\n\n\n\n\n\n\nanthony jeselnik thoughts and prayers   full transcript  scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
bill      \n\n\n\n\n\n\n\nbill burr im sorry you feel that way   full transcript  scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
bo        \n\n\n\n\n\n\n\nscraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
dave      \n\n\n\n\n\n\n\ndave chappelle the age of spin   transcript  scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
dylan     \n\n\n\n\n\n\n\ndylan moran yeah yeah   transcript  scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
hasan     \n\n\n\n\n\n\n\nscraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
jamie     \n\n\n\n\n\n\n\njamie foxx what had happened was   transcript  scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
jim       \n\n\n\n\n\n\n\njim jefferies bare   full transcript  scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
joe       \n\n\n\n\n\n\n\njoe rogan triggered   transcript  scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
john      \n\n\n\n\n\n\n\njohn mulaney the comeback kid   transcript  scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
kelsey    \n\n\n\n\n\n\n\nkelsey cook the hustler   transcript  scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
kevin     \n\n\n\n\n\n\n\nkevin james irregardless   transcript  scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
louis     \n\n\n\n\n\n\n\nlouis ck oh my god   transcript  scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
mike      \n\n\n\n\n\n\n\nmike birbiglia my girlfriends boyfriend   transcript  scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
ramy      \n\n\n\n\n\n\n\nramy youssef more feelings   transcript  scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
ricky     \n\n\n\n\n\n\n\nricky gervais humanity   transcript  scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
sal       \n\n\n\n\n\n\n\nsal vulcano terrified   transcript  scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
seth      \n\n\n\n\n\n\n\nseth meyers dad man walking   transcript  scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...

In [17]:
# Apply a second round of cleaning
def clean_text_round2(text):
    '''Get rid of some additional punctuation and non-sensical text that was missed the first time around.'''
    text = re.sub('[’‘“”…]', '', text)
    text = re.sub('\n', '', text)
    return text

round2 = lambda x: clean_text_round2(x)

In [18]:
# Let's take a look at the updated text
data_clean = pd.DataFrame(data_clean.transcript.apply(round2))
data_clean

                                                                                                                                                    transcript
adam      adam sandler love you   transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsmovie transcriptstv...
ali       ali wong baby cobra   transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsmovie transcriptstv s...
anthony   anthony jeselnik thoughts and prayers   full transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie revie...
bill      bill burr im sorry you feel that way   full transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie review...
bo        scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsmovie transcriptstv seriestv show transcriptscomedystan...
dave      dave chappelle the age of spin   transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsmovie tran...
dylan     dylan moran yeah yeah   transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsmovie transcriptstv...
hasan     scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsmovie transcriptstv seriestv show transcriptscomedystan...
jamie     jamie foxx what had happened was   transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsmovie tr...
jim       jim jefferies bare   full transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsmovie transcripts...
joe       joe rogan triggered   transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsmovie transcriptstv s...
john      john mulaney the comeback kid   transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsmovie trans...
kelsey    kelsey cook the hustler   transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsmovie transcripts...
kevin     kevin james irregardless   transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsmovie transcript...
louis     louis ck oh my god   transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsmovie transcriptstv se...
mike      mike birbiglia my girlfriends boyfriend   transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsm...
ramy      ramy youssef more feelings   transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsmovie transcri...
ricky     ricky gervais humanity   transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsmovie transcriptst...
sal       sal vulcano terrified   transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsmovie transcriptstv...
seth      seth meyers dad man walking   transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsmovie transcr...

## Organizing The Data

### Assignment:
1. Organized data in two standard text formats:
   a) Corpus - corpus is a collection of texts, and they are all put together neatly in a pandas dataframe here.
   b) Document-Term Matrix - word counts in matrix format

### Corpus: Example

A corpus is a collection of texts, and they are all put together neatly in a pandas dataframe here.

In [19]:
# Let's take a look at our dataframe
data_df

                                                                                                                                                    transcript
adam      \n\n\n\n\n\n\n\nAdam Sandler: Love You (2024) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
ali       \n\n\n\n\n\n\n\nAli Wong: Baby Cobra (2016) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
anthony   \n\n\n\n\n\n\n\nAnthony Jeselnik: Thoughts And Prayers (2015) - Full Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
bill      \n\n\n\n\n\n\n\nBILL BURR: I'M SORRY YOU FEEL THAT WAY (2014) - Full Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
bo        \n\n\n\n\n\n\n\nScraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
dave      \n\n\n\n\n\n\n\nDave Chappelle: The Age of Spin (2017) - Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
dylan     \n\n\n\n\n\n\n\nDylan Moran: Yeah, Yeah (2011) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
hasan     \n\n\n\n\n\n\n\nScraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
jamie     \n\n\n\n\n\n\n\nJamie Foxx: What Had Happened Was... (2024) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
jim       \n\n\n\n\n\n\n\nJIM JEFFERIES: BARE (2014) - Full Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
joe       \n\n\n\n\n\n\n\nJoe Rogan: Triggered (2016) - Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
john      \n\n\n\n\n\n\n\nJohn Mulaney: The Comeback Kid (2015) - Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
kelsey    \n\n\n\n\n\n\n\nKelsey Cook: The Hustler (2023) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
kevin     \n\n\n\n\n\n\n\nKevin James: Irregardless (2024) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
louis     \n\n\n\n\n\n\n\nLouis C.K.: Oh My God (2013) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
mike      \n\n\n\n\n\n\n\nMike Birbiglia: My Girlfriend's Boyfriend (2013) - Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
ramy      \n\n\n\n\n\n\n\nRamy Youssef: More Feelings (2024) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
ricky     \n\n\n\n\n\n\n\nRicky Gervais: Humanity (2018) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...
sal       \n\n\n\n\n\n\n\nSal Vulcano: Terrified (2024) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
seth      \n\n\n\n\n\n\n\nSeth Meyers: Dad Man Walking (2024) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...

In [20]:
# Let's add the comedians' full names as well
full_names = ['Adam Sandler', 'Ali Wong', 'Anthony Jeselnik', 'Bill Burr', 'Bo Burnham',  'Dave Chappelle', 'Dylan Moran', 'Hasan Minhaj', 'Jamie Foxx', 
              'Jim Jefferies', 'Joe Rogan', 'John Mulaney', 'Kelsey Cook', 'Kevin James', 'Louis C.K.', 'Mike Birbiglia', 'Ramy Youssef', 'Ricky Gervais', 'Sal Vulcano', 'Seth Meyers']

data_df['full_name'] = full_names
data_df

,transcript,full_name
adam,\n\n\n\n\n\n\n\nAdam Sandler: Love You (2024) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,Adam Sandler
ali,\n\n\n\n\n\n\n\nAli Wong: Baby Cobra (2016) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,Ali Wong
anthony,\n\n\n\n\n\n\n\nAnthony Jeselnik: Thoughts And Prayers (2015) - Full Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...,Anthony Jeselnik
bill,\n\n\n\n\n\n\n\nBILL BURR: I'M SORRY YOU FEEL THAT WAY (2014) - Full Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...,Bill Burr
bo,\n\n\n\n\n\n\n\nScraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,Bo Burnham
dave,\n\n\n\n\n\n\n\nDave Chappelle: The Age of Spin (2017) - Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...,Dave Chappelle
dylan,"\n\n\n\n\n\n\n\nDylan Moran: Yeah, Yeah (2011) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...",Dylan Moran
hasan,\n\n\n\n\n\n\n\nScraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,Hasan Minhaj
jamie,\n\n\n\n\n\n\n\nJamie Foxx: What Had Happened Was... (2024) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,Jamie Foxx
jim,\n\n\n\n\n\n\n\nJIM JEFFERIES: BARE (2014) - Full Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,Jim Jefferies
joe,\n\n\n\n\n\n\n\nJoe Rogan: Triggered (2016) - Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,Joe Rogan
john,\n\n\n\n\n\n\n\nJohn Mulaney: The Comeback Kid (2015) - Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,John Mulaney
kelsey,\n\n\n\n\n\n\n\nKelsey Cook: The Hustler (2023) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,Kelsey Cook
kevin,\n\n\n\n\n\n\n\nKevin James: Irregardless (2024) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...,Kevin James
louis,\n\n\n\n\n\n\n\nLouis C.K.: Oh My God (2013) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...,Louis C.K.
mike,\n\n\n\n\n\n\n\nMike Birbiglia: My Girlfriend's Boyfriend (2013) - Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...,Mike Birbiglia
ramy,\n\n\n\n\n\n\n\nRamy Youssef: More Feelings (2024) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...,Ramy Youssef
ricky,\n\n\n\n\n\n\n\nRicky Gervais: Humanity (2018) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...,Ricky Gervais
sal,\n\n\n\n\n\n\n\nSal Vulcano: Terrified (2024) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,Sal Vulcano
seth,\n\n\n\n\n\n\n\nSeth Meyers: Dad Man Walking (2024) | Transcript - Scraps from the loft\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,Seth Meyers

In [21]:
# Let's pickle it for later use
data_df.to_pickle("corpus.pkl")

### Document-Term Matrix: Example

For many of the techniques we'll be using in future assignment, the text must be tokenized, meaning broken down into smaller pieces. The most common tokenization technique is to break down text into words. We can do this using scikit-learn's ` CountVectorizer `, where every row will represent a different document and every column will represent a different word.

In addition, with ` CountVectorizer `, we can remove stop words. Stop words are common words that add no additional meaning to text such as 'a', 'the', etc.

In [22]:
# We are going to create a document-term matrix using CountVectorizer, and exclude common English stop words
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words='english')
data_cv = cv.fit_transform(data_clean.transcript)
data_dtm = pd.DataFrame(data_cv.toarray(), columns=cv.get_feature_names_out())
data_dtm.index = data_clean.index
data_dtm

,aa,aaaaah,aaah,aah,aback,abbott,abc,abcs,ability,abject,...,zero,zillion,zingy,zipup,zombie,zombies,zoning,zoo,zoom,éclair
adam,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
ali,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bill,0,1,0,0,0,0,0,1,0,0,...,1,1,0,0,1,1,1,0,0,0
bo,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
dave,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
dylan,0,0,0,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,2
hasan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
jamie,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
kelsey,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
kevin,0,0,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,0,0,0,0
louis,0,0,0,3,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
ramy,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
ricky,0,0,0,0,0,0,0,0,2,1,...,0,0,0,0,0,0,0,1,0,0
sal,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
seth,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
# Let's pickle it for later use
data_dtm.to_pickle("dtm.pkl")

In [24]:
# Let's also pickle the cleaned data (before we put it in document-term matrix format) and the CountVectorizer object
data_clean.to_pickle('data_clean.pkl')
pickle.dump(cv, open("cv.pkl", "wb"))

## Additional Assignments:

1. Can you add an additional regular expression to the clean_text_round2 function to further clean the text?
2. Play around with CountVectorizer's parameters. What is ngram_range? What is min_df and max_df?

In [25]:
data_clean.iloc[0, 0]

' adam sandler love you   transcript  scraps from the loft \t\tskip to content \t\t\t\t\t\tsearch\t\t\t\t\t  moviesmovie reviewsmovie transcriptstv seriestv show transcriptscomedystandup comedy transcriptsgeorge carlindave chappelleinterviewsplayboy interviewsmusichistorybooksopinions  moviesmovie reviewsmovie transcriptstv seriestv show transcriptscomedystandup comedy transcriptsgeorge carlindave chappelleinterviewsplayboy interviewsmusichistorybooksopinions comedy adam sandler love you   transcript august   \t\t\t\t\tafter a rather oddly chaotic beginning adam arrives late to the gig driving a car with a broken windshield the show gains momentum two songs exemplify typical sandler humor bulldog in a halloween costume and the drone song\t\t\t\t  back up back up♪ its gonna take a lotta love ♪ ♪ to get us through the night ♪yo vil what happened i thought you guys were fixing this shit im driving in the car like this putting my head out the window spilled fuckin coffee itll be done boss sorry bout that ill get ya after the show i think im late i think im late ill get you guys after whats up whats up whats up how are we doing on time doing good hows lester doing adamask him ask him now hey young man how are you what are you doing out so late with all these crazy people what do you got what is this is this me me in my house we got these in manhattanthey sell photos of movie starsyou did you know this kidyoure a movie star hes my sonthats your son whens whens his birthdaytell him when your birthday isno you tell him when his birthday is i had covid i lost memory of that your grandmothers a sick woman come on you said youd sign for children this waydont be mad i gotta do the show ill see you in there ill see you ill get it right after so go in herewhy didnt they lock up the alley i tried theyre shortstaffed dont want some chinese food what no im not eating ill throw it outi gotta change my shirt dressing roomsum is this the stage you know the stiff neck is better than one of these deals  hows he doinghes doin good this is a person with a stiff neck watching a pro tennis player hit an ace oh aces dont come backwho booked this place not mewell its adambergie my god this is the worst moment of my life youre here hows it going skip nice to meet you i work with bergie ill pay you  to murder this man right now thats not funny we gotta get this stuff donei got goddamn coffee all over this shirt you want one of these shirts i dont know i need a hoodiewant this onethatd be its an xl i dont know if were in the same weight class but alright put this shit on actually just keep it offgive him a thrill would youoh stopwould you sign this stuffi cant do it now we got  pieces to do its for ms charity i got a show to do bergiewe gotta go were lateyeah i know bergie bergie bergie i got it give me the shit i know i gotta i cant do them all right now you gotta get them done well get it to youno its for ms i gotta do this shit let me just there was a kid outside i was a dick to does he have ms no then absolutely not this goes to ms give him a fucking putter thank you buddy come on lets gonice to meet you adamthanks for the sweatshirtheres your coffeesteviaof course going down the stairs have a good set im gonna play some of the synths in comedy live if thats cool yeah surebees maple syrup we cut oh let me do that if i want towell see what happens alright its in there jellyfish ohwhose dog is that dunno this place is crazy what the fuck is going on left and left okay left and a left locked door we have the second verse there right nowis that cool yeah its uh okay i think we should try a vocoder is that cool yeah yeah thatll be funny so i justi just sing normal you do it totally normallyalright everything you do is the same excuse me mr sandler im sorry to interrupt you not at all whats doing wonder if you could do me a big favor and say a few words to my son jamesabsolutelyhes in the hospital let me do this show oh hes in the hospital he had a big accident on his scooterim sorry to hear thathe really injured himself and hes a big fan of yours alright ill seejames hes here ive got mr sandler right here ohhey jamesno way no wayyeah – is that mr sandlerhey man – oh my god you landed on your face huh bro mr sandler im not feeling goodi see that – please come see me in the hospital i would love to see you man  im doing a comedy show right now youre going to be okay mr sandler i promise im not gonna make itill see ya adamdefinitelygood showthank youalright ill set uphave a good showadam yeah yeah im sorry pardon me great audienceyou were fantastic thank you so muchyou guys were greatthey made me feel real willie and lester you guys ladies and gentlementhis means a lot to me the crowd loves you appreciate that please give it up for mr adam sandler go get em adamlets go take care break a leg that was already insane i dont know what happened ladies and gentlemen thank youthank you very much thank you alright dont do that i love ya alright hi hi how are you alright guys bulla nice to see you all whats up hi guysalright i love you thank you so much alright we got a whole show alright thanks a lot everybody i love you thanks for coming out whats going on with thewhy is that doing thatwhys the were working on it a computer issue were working on it got a computer alright so what you want to wait for should i wait no no lets not wait lets keep going were gonna get them working itll be fine lets just go alright yeah alright okay so just go and well do this because we got so many things that were supposed to show up there alright its alrightwell well no no no thats what its gonna look like i dont know were gonna kill them this is uhh splenda you put in here you fucked me it was supposed to be stevia lets kill the monitors pleasejust kill the monitors yeah just go to blackyeah alrightladies and gentlemen what a thank youalright alright so i was eating grapesi was eating some grapes it was going goodthis guy i was with goes youi was like what what he goes you youve changed i said get out of here i always liked grapes and uh hes like i dont like this version of you and i said fuck ive been eating grapes my whole life calm the fuck down he goes im leaving i said well get outta here then ive had enough of you too so anyways he left and then i said to the man who was feeding me the grapes i said what do you think you think i changed and hes like no and i go he changed right he goes yeah he changed sandman a woman outside said to me hey i got a tattoo of you on my calf i was like alright that looks good and shes like yeah i like it too and then her husband goes adam can i talk to you come here for a minute i go whats up dude he goes you think i like that bullshit fuckin makin love to my wife got her legs up here i look over i see your fucking ugly face you think i like that bullshit i go oh well you dont gotta look he goes how am i gonna finish adam ive grown accustomed to your face i got a letter recently from a man i opened it up and it says my name is charlie mungo i am onefoot tall and im gonna shoot you i was like uhohanyways a couple weeks goes by i get this another letter open it up its me charlie mungo still one foot youre fucking dead sandman i was like whoa shit this guy means business couple weeks goes by same kind of scribblescrabble on this envelope i go here we go i open it up it says fuck you you dont deserve to live sandman this is charlie mungo you will pay for your sins  ps still onefoot tall i was like fuck man my friends were like you gotta report that shit thats gotta go to the fbi you know i said you know what fuck it im not telling nobody cause then charlie mungo wins gotta just live my life you know you know what im saying i did get bulletproof socksso uhum what happened yes so what is that huh coffee with steviahuh sorry it was splenda it was splendayoure goodim good man i fucking knew itwell i love you im glad you were honest mmhmm  thats stevia yeah thank you buddy thanks for confessing why dont you shut the fuck up with that laughing hang on hang oneverything okay over here shut the fuck up they wont be quietwho wont be quiet he threatened to put him in his placeoh you guys dont worry because were laughing alright well everyone laughs in in their own way  how about you dont look at each other the whole show but you can fucking laugh you guys laugh you guys laugh then after the show well all get in a massive fightalright dont worry i love you you guys just have a good time♪ shes got long brown hair tied up in a little red bonnet ♪ ♪ shes got a pretty white blouse and a basket with fresh fruit upon it ♪ ♪ shes got a glow in her cheeks and a fire inside ♪ ♪ sitting in a beautiful countryside ♪ ♪ oh masturbating to the lady on the box of raisins ♪ alright so that  it was supposed to be uh you were supposed to show her up theregoddammit were working on it i think we have a the computers are very old just trying to figure out nobody wanted to chip in and get a fucking new one  i was uh at a restaurant recently i was eating a hamburger having a nice time a guy comes up and says can i take a picture of your hamburger i said uh how come he said im from spain i said you guys got hamburgers he goes yeah but thats a big juicy one  so i go alright take the picture bro then like  minutes hes taking a picture of another guys hamburger and i go whats going on bro and he goes this ones bigger and then i go well fucking delete mine theni uh  i took the family to the fuckin circus were having a good time the clown car comes out they got  fucking clowns in one little tiny car my kids were like holy shit how they doin it i said i dont know theyre fucking pros anyway we were driving home the kids are still talking about it fucking incredible all of a sudden the little car rolls up next to us on the highway im like kids look over there all  fucking clowns are in there my kids are like yeah great show theyre like smoking butts like yeah whassup you know its all good baby alright and then they hit an oil slick and they fucking spin i was like holy shit and it fucking kept spinning and shit my kids are like whats happening then they hit the guardrail i was like oh no theyre sliding across i hit the fucking brakes it goes right past it hits the truck fuckin blows up we were like did we just see that shit that was horrible my kids are crying i was like goodness gracious this night changed anyways we went to the funeral and uh we get there one coffin all  of them and i was like they still got it man these fucking guys still got it thank you so much you guys are my best friends thank youyeah yeah♪ shes the happiest shes been in years ♪ ♪ he puts on a big smile on her face ♪oh shit whoa you son of a bitchthats gonna happen thats all fineits all part of the plan what happened uh why did that happen its a fucking theres a hole in the groundalrighttheres a hole in the stage its all working out tonight so what do we do right nowso we do the whole show like thisdigby yeahwhats up buddy thank you so much thank you will you see if theres a good monitor down there too yeah yeah lets alrightlaurenlaurenthank you sorry everybody were gonna get this right i like that chicken parm shirt thats funny we could just do what is that oh a fucking lunch tray theres no way thats going to work theres no way are you fucking kidding menice job holy shit you guys are good this is a bad sign everybody okay lets go♪ shes the happiest shes been in years ♪ ♪ he puts a big smile on her face ♪ ♪ hes got a good job and me and my parents love the dude ♪ ♪ you can tell that hes gonna be faithful ♪ ♪ the whole family is happy as hell ♪ ♪ my sisters got an ugly new boyfriend ♪ thank you thank you we needed that one guys we needed that one hooalright alright lets see what we got here hmm lets see how we do on this one a little guitar only if you encourage me with some applause you want some guitarhere we go♪ every day im mutterin ♪ ♪ mutterin under my breath ♪hyah  ♪ if you ask me to do a task ♪ hyah  ♪ i do it every time ♪ hyah  ♪ but the whole time that im doing it ♪  ♪ ill be mutterin under my breath ♪  how come i gotta do this fucking shit no one else could have done it im fucking sick of this crap man all they do is sit there all day i do every fucking thing in this house fuck these people  ♪ things id never say to your face ♪ hyah  ♪ but the second that youre gone ♪ hyah  ♪ i mutter like a crazy asshole ♪  ♪ while i angrily mow the lawn ♪ how come im fucking mowing this shit goddamn this fucking house they cant do nothin fuckin they know how to start this fuckin thing fucking bullshit its always me the fuckin grass just grows back why the fuck am i out here i cant stand these motherfuckers ♪ rake the leaves ♪ ♪ im mutterin ♪ ♪ shovel snow ♪ im  ♪ im mutterin ♪ ♪ go to the bank ♪ ♪ you know im mutterin ♪ ♪ take out the trash ♪ ♪ theres mutterin ♪ ♪ when theres toys at the bottom of the pool ♪ ♪ left there by my daughter ♪ ♪ as i swim down to get them ♪ ♪ ill be mutterin underwater ♪  you cant get your own fucking toys or at least buy fucking toys that float what the fuck has happened to my fucking life  ♪ everyday im mutterin ♪ hyah  ♪ mutterin under my breath ♪   ♪ then one day my wife overhears what im saying ♪ ♪ and immediately slits ♪ ♪ my throat ♪ you guys are the fucking best i love you i love you i need you help me so my grandparents retired and that was nice and then my grandmother panicked shes like oh no we have no income how we gonna pay for things so she opened a kissing booth in our driveway she built a little booth put a little sign  a kiss every car was just whizzing past my grandfather comes outgives her  and gave her a kiss and then he gave her another  gave her a longer kiss then he gave her another  kind of a deeper mouthopen kind of thing went up the back of the thing snapped the fucking bra pulled the bra out whipped it on the ground got the hands rolling the belt line then got the hand in went some buns a little bunsmacking went down the middle finger tapping and shit and then we were all like this is fucked up uh because it was my other grandfatheryeah  they used to flirt but we didnt know we didnt see that coming uh  um yeah so i uh my wife is younger than meanybody have a younger wife hereyou do right you understand what im saying my wifes eight years younger than me that was fine when we were young because now that were older she still looks good im starting to look a little beaten know what i mean and i dont wanna i dont want to do plastic surgery ill never do that i did try botox on my dick i botoxed my dick i wanted to make her a fresheningup give her a better a youngerlooking dick to slap around i felt like i felt bad for her my dick was starting to get a little a little wornlooking you know a little almost like it needed a cane it was always kind of leaning scoliosis dick kind of leaning on the right ball my left ball was always like how the fuck do i get left out my right ball was like shh youre gonna wake him let him rest hes tiredbut anyways i botoxed my dick fellas i know youre saying you can do that dont do it youre better than that you dont need that shit so i botoxed mine the problem is it takes the wrinkles away a flaccid penis needs wrinkles to show that its flaccid you know thats why god gave you wrinkles for a reason pull your pants down a girl sees you go no it gets better than that you just gotta wait anyways i took the wrinkles away im in the fucking goddamn uh ymca locker room im naked a couple of guys walk in i hear you got a boner i go no no they go thats a boner i go thats not a boner they go no wrinkles thats a fullon hardon i go no this is botox i botoxed my dick they go thats a full raging hardon thats a younglooking dick like it belongs on a thirdgrader i go thats cause its not a fucking boner this is a normal fucking flaccid dick i said would a boner face down they go yours does i said shut the fuck up man dont worry about my dick just you get fucking dressed and leave me alone so anyways i went home i was disappointed reeling from the insults and shit im very close to my dog so my dog comes in and goes whats up what happened i go what my dogs like you look so sad i go ah that fucking ymca he goes what i go the fucking guys were making fun of me he goes what what i go i fucking botoxed my dick he goes i saw i remember and i go and i go well they fucking were saying i had a boner and shit he goes did you i go yeah but  no i didnt i didnt have a boner man it was a fucking normal flaccid dick but he goes hey hey heres what you do you paint it pink and i go why he goes i have a pink dick i said i know ive seen that he goes everybody loves it i go nobody loves your pink thing he goes the fuck you talking about every time my pink dick comes out i always hear look at the pink dick on the dog look how pink his cock is no one talks about big or small theyre like that is the pinkest fucking wettestlooking cock ive ever seen its bringing so much joy to me and they hug and laugh and highfive thats what a dick should do man and im like i dunno he goes will you at least think about it i go yeah ill think about it then i look down through the fur this pink hog starts oozing out growing and growing i go what is happening he goes im just excited youll think about it yes yes♪ driving back from disneyland ♪ ♪ going over all the fun ♪ ♪ what was best space mountain ♪ ♪ or getting wet on the grizzly river run yeah ♪ ♪ greatest time of our kids life ♪ ♪ what a magical moment for me and my wife ♪ ♪ then i miss our exit ♪ ♪ and i scream fucking cunt ♪ ♪ and its like disneyland never happened ♪thats a mistake and my kids uh the fucking best time of your life with your kids right dont you love your kids more than anything i remember when my daughter was born ill never forget what my father said my father said youre gonna drop the baby thats going to happen i go oh okay he goes that shit happens thats life  you drop the baby fuck it but you pick the baby up and you dont fucking make a big fuss because the babys gonna be like what the fuck that wasnt supposed to happen you play it off like thats life you pick the baby up look at it you go whats up youre alright okay i guess dad no no thats life you drop the baby what are you gonna do youre busy you got the fucking groceries in your hand you got you got the baby drop the baby you got the groceries you look down put the baby on your foot you fuckin kick it up catch the baby you keep going you look at the baby hey how you doing man everything good the babys like i guess yeah thats life you know hes like i fucking dropped your little brother fucking   times i go i got a little brother he goes you didbut uh  my father  my father used to always go for the belt hed be like youre gonna get the belt fucking i dont do that with my kids just cause i wear sweatpants im like youre gonna get the tassels daddy gonna daddy gonna get you i went to the daddy  i went to the daddydaughter dance recently she didnt fucking show son of a bitch standing there with a corsageheartbroken  by the way if this could work it would be great honestly would it can it workno not to be a dick if i knew it was gonna take this long obviously id have waited – youre doing a good jobyou sound snippy though dont you sound a little snippy for a guy who fucked me this hard were working on it dont worry about italright ♪ sleep in late ♪ ♪ eat a big breakfast ♪ ♪ walk the dog ♪ ♪ watch the news ♪ ♪ go to the bathroom ♪ ♪ start my laundry ♪ ♪ go on the internet ♪ ♪ buy some new shoes ♪ ♪ leave the apartment for lunch with my landlord ♪ ♪ come back home ♪ ♪ take the dog for a walk again ♪ ♪ turn on my tv ♪ ♪ watch jerry maguire ♪ ♪ ive seen it before ♪ ♪ but ill watch it again ♪ ♪ pretty good day ♪ ♪ pretty good life ♪ ♪ i am clinically depressed ♪alright sorry so uh im sorry that was ehh  so im at the fucking airport ever have a guy say to you hey can you watch my bag

In [ ]:
def clean_text_round2(text):
    '''Enhancing the function'''
    text = re.sub('[’‘“”…]', '', text)
    text = re.sub('\n', '', text)
    text = re.sub(r'\t+', ' ', text) # Remove tabs and replace them with space 
    text = re.sub(r' +', ' ', text)
    return text.strip()

round2 = lambda x: clean_text_round2(x)

In [27]:
data_clean.transcript = data_clean.transcript.apply(round2)
data_clean

                                                                                                                                                    transcript
adam     adam sandler love you transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv show transcriptscomed...
ali      ali wong baby cobra transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv show transcriptscomedys...
anthony  anthony jeselnik thoughts and prayers full transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv ...
bill     bill burr im sorry you feel that way full transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv s...
bo       scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv show transcriptscomedystandup comedy transcriptsgeorge...
dave     dave chappelle the age of spin transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv show transcr...
dylan    dylan moran yeah yeah transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv show transcriptscomed...
hasan    scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv show transcriptscomedystandup comedy transcriptsgeorge...
jamie    jamie foxx what had happened was transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv show trans...
jim      jim jefferies bare full transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv show transcriptscom...
joe      joe rogan triggered transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv show transcriptscomedys...
john     john mulaney the comeback kid transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv show transcri...
kelsey   kelsey cook the hustler transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv show transcriptscom...
kevin    kevin james irregardless transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv show transcriptsco...
louis    louis ck oh my god transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv show transcriptscomedyst...
mike     mike birbiglia my girlfriends boyfriend transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv sho...
ramy     ramy youssef more feelings transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv show transcripts...
ricky    ricky gervais humanity transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv show transcriptscome...
sal      sal vulcano terrified transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv show transcriptscomed...
seth     seth meyers dad man walking transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv show transcript...

In [28]:
data_clean.iloc[0, 0]

'adam sandler love you transcript scraps from the loft skip to content search moviesmovie reviewsmovie transcriptstv seriestv show transcriptscomedystandup comedy transcriptsgeorge carlindave chappelleinterviewsplayboy interviewsmusichistorybooksopinions moviesmovie reviewsmovie transcriptstv seriestv show transcriptscomedystandup comedy transcriptsgeorge carlindave chappelleinterviewsplayboy interviewsmusichistorybooksopinions comedy adam sandler love you transcript august after a rather oddly chaotic beginning adam arrives late to the gig driving a car with a broken windshield the show gains momentum two songs exemplify typical sandler humor bulldog in a halloween costume and the drone song back up back up♪ its gonna take a lotta love ♪ ♪ to get us through the night ♪yo vil what happened i thought you guys were fixing this shit im driving in the car like this putting my head out the window spilled fuckin coffee itll be done boss sorry bout that ill get ya after the show i think im late i think im late ill get you guys after whats up whats up whats up how are we doing on time doing good hows lester doing adamask him ask him now hey young man how are you what are you doing out so late with all these crazy people what do you got what is this is this me me in my house we got these in manhattanthey sell photos of movie starsyou did you know this kidyoure a movie star hes my sonthats your son whens whens his birthdaytell him when your birthday isno you tell him when his birthday is i had covid i lost memory of that your grandmothers a sick woman come on you said youd sign for children this waydont be mad i gotta do the show ill see you in there ill see you ill get it right after so go in herewhy didnt they lock up the alley i tried theyre shortstaffed dont want some chinese food what no im not eating ill throw it outi gotta change my shirt dressing roomsum is this the stage you know the stiff neck is better than one of these deals hows he doinghes doin good this is a person with a stiff neck watching a pro tennis player hit an ace oh aces dont come backwho booked this place not mewell its adambergie my god this is the worst moment of my life youre here hows it going skip nice to meet you i work with bergie ill pay you to murder this man right now thats not funny we gotta get this stuff donei got goddamn coffee all over this shirt you want one of these shirts i dont know i need a hoodiewant this onethatd be its an xl i dont know if were in the same weight class but alright put this shit on actually just keep it offgive him a thrill would youoh stopwould you sign this stuffi cant do it now we got pieces to do its for ms charity i got a show to do bergiewe gotta go were lateyeah i know bergie bergie bergie i got it give me the shit i know i gotta i cant do them all right now you gotta get them done well get it to youno its for ms i gotta do this shit let me just there was a kid outside i was a dick to does he have ms no then absolutely not this goes to ms give him a fucking putter thank you buddy come on lets gonice to meet you adamthanks for the sweatshirtheres your coffeesteviaof course going down the stairs have a good set im gonna play some of the synths in comedy live if thats cool yeah surebees maple syrup we cut oh let me do that if i want towell see what happens alright its in there jellyfish ohwhose dog is that dunno this place is crazy what the fuck is going on left and left okay left and a left locked door we have the second verse there right nowis that cool yeah its uh okay i think we should try a vocoder is that cool yeah yeah thatll be funny so i justi just sing normal you do it totally normallyalright everything you do is the same excuse me mr sandler im sorry to interrupt you not at all whats doing wonder if you could do me a big favor and say a few words to my son jamesabsolutelyhes in the hospital let me do this show oh hes in the hospital he had a big accident on his scooterim sorry to hear thathe really injured himself and hes a big fan of yours alright ill seejames hes here ive got mr sandler right here ohhey jamesno way no wayyeah – is that mr sandlerhey man – oh my god you landed on your face huh bro mr sandler im not feeling goodi see that – please come see me in the hospital i would love to see you man im doing a comedy show right now youre going to be okay mr sandler i promise im not gonna make itill see ya adamdefinitelygood showthank youalright ill set uphave a good showadam yeah yeah im sorry pardon me great audienceyou were fantastic thank you so muchyou guys were greatthey made me feel real willie and lester you guys ladies and gentlementhis means a lot to me the crowd loves you appreciate that please give it up for mr adam sandler go get em adamlets go take care break a leg that was already insane i dont know what happened ladies and gentlemen thank youthank you very much thank you alright dont do that i love ya alright hi hi how are you alright guys bulla nice to see you all whats up hi guysalright i love you thank you so much alright we got a whole show alright thanks a lot everybody i love you thanks for coming out whats going on with thewhy is that doing thatwhys the were working on it a computer issue were working on it got a computer alright so what you want to wait for should i wait no no lets not wait lets keep going were gonna get them working itll be fine lets just go alright yeah alright okay so just go and well do this because we got so many things that were supposed to show up there alright its alrightwell well no no no thats what its gonna look like i dont know were gonna kill them this is uhh splenda you put in here you fucked me it was supposed to be stevia lets kill the monitors pleasejust kill the monitors yeah just go to blackyeah alrightladies and gentlemen what a thank youalright alright so i was eating grapesi was eating some grapes it was going goodthis guy i was with goes youi was like what what he goes you youve changed i said get out of here i always liked grapes and uh hes like i dont like this version of you and i said fuck ive been eating grapes my whole life calm the fuck down he goes im leaving i said well get outta here then ive had enough of you too so anyways he left and then i said to the man who was feeding me the grapes i said what do you think you think i changed and hes like no and i go he changed right he goes yeah he changed sandman a woman outside said to me hey i got a tattoo of you on my calf i was like alright that looks good and shes like yeah i like it too and then her husband goes adam can i talk to you come here for a minute i go whats up dude he goes you think i like that bullshit fuckin makin love to my wife got her legs up here i look over i see your fucking ugly face you think i like that bullshit i go oh well you dont gotta look he goes how am i gonna finish adam ive grown accustomed to your face i got a letter recently from a man i opened it up and it says my name is charlie mungo i am onefoot tall and im gonna shoot you i was like uhohanyways a couple weeks goes by i get this another letter open it up its me charlie mungo still one foot youre fucking dead sandman i was like whoa shit this guy means business couple weeks goes by same kind of scribblescrabble on this envelope i go here we go i open it up it says fuck you you dont deserve to live sandman this is charlie mungo you will pay for your sins ps still onefoot tall i was like fuck man my friends were like you gotta report that shit thats gotta go to the fbi you know i said you know what fuck it im not telling nobody cause then charlie mungo wins gotta just live my life you know you know what im saying i did get bulletproof socksso uhum what happened yes so what is that huh coffee with steviahuh sorry it was splenda it was splendayoure goodim good man i fucking knew itwell i love you im glad you were honest mmhmm thats stevia yeah thank you buddy thanks for confessing why dont you shut the fuck up with that laughing hang on hang oneverything okay over here shut the fuck up they wont be quietwho wont be quiet he threatened to put him in his placeoh you guys dont worry because were laughing alright well everyone laughs in in their own way how about you dont look at each other the whole show but you can fucking laugh you guys laugh you guys laugh then after the show well all get in a massive fightalright dont worry i love you you guys just have a good time♪ shes got long brown hair tied up in a little red bonnet ♪ ♪ shes got a pretty white blouse and a basket with fresh fruit upon it ♪ ♪ shes got a glow in her cheeks and a fire inside ♪ ♪ sitting in a beautiful countryside ♪ ♪ oh masturbating to the lady on the box of raisins ♪ alright so that it was supposed to be uh you were supposed to show her up theregoddammit were working on it i think we have a the computers are very old just trying to figure out nobody wanted to chip in and get a fucking new one i was uh at a restaurant recently i was eating a hamburger having a nice time a guy comes up and says can i take a picture of your hamburger i said uh how come he said im from spain i said you guys got hamburgers he goes yeah but thats a big juicy one so i go alright take the picture bro then like minutes hes taking a picture of another guys hamburger and i go whats going on bro and he goes this ones bigger and then i go well fucking delete mine theni uh i took the family to the fuckin circus were having a good time the clown car comes out they got fucking clowns in one little tiny car my kids were like holy shit how they doin it i said i dont know theyre fucking pros anyway we were driving home the kids are still talking about it fucking incredible all of a sudden the little car rolls up next to us on the highway im like kids look over there all fucking clowns are in there my kids are like yeah great show theyre like smoking butts like yeah whassup you know its all good baby alright and then they hit an oil slick and they fucking spin i was like holy shit and it fucking kept spinning and shit my kids are like whats happening then they hit the guardrail i was like oh no theyre sliding across i hit the fucking brakes it goes right past it hits the truck fuckin blows up we were like did we just see that shit that was horrible my kids are crying i was like goodness gracious this night changed anyways we went to the funeral and uh we get there one coffin all of them and i was like they still got it man these fucking guys still got it thank you so much you guys are my best friends thank youyeah yeah♪ shes the happiest shes been in years ♪ ♪ he puts on a big smile on her face ♪oh shit whoa you son of a bitchthats gonna happen thats all fineits all part of the plan what happened uh why did that happen its a fucking theres a hole in the groundalrighttheres a hole in the stage its all working out tonight so what do we do right nowso we do the whole show like thisdigby yeahwhats up buddy thank you so much thank you will you see if theres a good monitor down there too yeah yeah lets alrightlaurenlaurenthank you sorry everybody were gonna get this right i like that chicken parm shirt thats funny we could just do what is that oh a fucking lunch tray theres no way thats going to work theres no way are you fucking kidding menice job holy shit you guys are good this is a bad sign everybody okay lets go♪ shes the happiest shes been in years ♪ ♪ he puts a big smile on her face ♪ ♪ hes got a good job and me and my parents love the dude ♪ ♪ you can tell that hes gonna be faithful ♪ ♪ the whole family is happy as hell ♪ ♪ my sisters got an ugly new boyfriend ♪ thank you thank you we needed that one guys we needed that one hooalright alright lets see what we got here hmm lets see how we do on this one a little guitar only if you encourage me with some applause you want some guitarhere we go♪ every day im mutterin ♪ ♪ mutterin under my breath ♪hyah ♪ if you ask me to do a task ♪ hyah ♪ i do it every time ♪ hyah ♪ but the whole time that im doing it ♪ ♪ ill be mutterin under my breath ♪ how come i gotta do this fucking shit no one else could have done it im fucking sick of this crap man all they do is sit there all day i do every fucking thing in this house fuck these people ♪ things id never say to your face ♪ hyah ♪ but the second that youre gone ♪ hyah ♪ i mutter like a crazy asshole ♪ ♪ while i angrily mow the lawn ♪ how come im fucking mowing this shit goddamn this fucking house they cant do nothin fuckin they know how to start this fuckin thing fucking bullshit its always me the fuckin grass just grows back why the fuck am i out here i cant stand these motherfuckers ♪ rake the leaves ♪ ♪ im mutterin ♪ ♪ shovel snow ♪ im ♪ im mutterin ♪ ♪ go to the bank ♪ ♪ you know im mutterin ♪ ♪ take out the trash ♪ ♪ theres mutterin ♪ ♪ when theres toys at the bottom of the pool ♪ ♪ left there by my daughter ♪ ♪ as i swim down to get them ♪ ♪ ill be mutterin underwater ♪ you cant get your own fucking toys or at least buy fucking toys that float what the fuck has happened to my fucking life ♪ everyday im mutterin ♪ hyah ♪ mutterin under my breath ♪ ♪ then one day my wife overhears what im saying ♪ ♪ and immediately slits ♪ ♪ my throat ♪ you guys are the fucking best i love you i love you i need you help me so my grandparents retired and that was nice and then my grandmother panicked shes like oh no we have no income how we gonna pay for things so she opened a kissing booth in our driveway she built a little booth put a little sign a kiss every car was just whizzing past my grandfather comes outgives her and gave her a kiss and then he gave her another gave her a longer kiss then he gave her another kind of a deeper mouthopen kind of thing went up the back of the thing snapped the fucking bra pulled the bra out whipped it on the ground got the hands rolling the belt line then got the hand in went some buns a little bunsmacking went down the middle finger tapping and shit and then we were all like this is fucked up uh because it was my other grandfatheryeah they used to flirt but we didnt know we didnt see that coming uh um yeah so i uh my wife is younger than meanybody have a younger wife hereyou do right you understand what im saying my wifes eight years younger than me that was fine when we were young because now that were older she still looks good im starting to look a little beaten know what i mean and i dont wanna i dont want to do plastic surgery ill never do that i did try botox on my dick i botoxed my dick i wanted to make her a fresheningup give her a better a youngerlooking dick to slap around i felt like i felt bad for her my dick was starting to get a little a little wornlooking you know a little almost like it needed a cane it was always kind of leaning scoliosis dick kind of leaning on the right ball my left ball was always like how the fuck do i get left out my right ball was like shh youre gonna wake him let him rest hes tiredbut anyways i botoxed my dick fellas i know youre saying you can do that dont do it youre better than that you dont need that shit so i botoxed mine the problem is it takes the wrinkles away a flaccid penis needs wrinkles to show that its flaccid you know thats why god gave you wrinkles for a reason pull your pants down a girl sees you go no it gets better than that you just gotta wait anyways i took the wrinkles away im in the fucking goddamn uh ymca locker room im naked a couple of guys walk in i hear you got a boner i go no no they go thats a boner i go thats not a boner they go no wrinkles thats a fullon hardon i go no this is botox i botoxed my dick they go thats a full raging hardon thats a younglooking dick like it belongs on a thirdgrader i go thats cause its not a fucking boner this is a normal fucking flaccid dick i said would a boner face down they go yours does i said shut the fuck up man dont worry about my dick just you get fucking dressed and leave me alone so anyways i went home i was disappointed reeling from the insults and shit im very close to my dog so my dog comes in and goes whats up what happened i go what my dogs like you look so sad i go ah that fucking ymca he goes what i go the fucking guys were making fun of me he goes what what i go i fucking botoxed my dick he goes i saw i remember and i go and i go well they fucking were saying i had a boner and shit he goes did you i go yeah but no i didnt i didnt have a boner man it was a fucking normal flaccid dick but he goes hey hey heres what you do you paint it pink and i go why he goes i have a pink dick i said i know ive seen that he goes everybody loves it i go nobody loves your pink thing he goes the fuck you talking about every time my pink dick comes out i always hear look at the pink dick on the dog look how pink his cock is no one talks about big or small theyre like that is the pinkest fucking wettestlooking cock ive ever seen its bringing so much joy to me and they hug and laugh and highfive thats what a dick should do man and im like i dunno he goes will you at least think about it i go yeah ill think about it then i look down through the fur this pink hog starts oozing out growing and growing i go what is happening he goes im just excited youll think about it yes yes♪ driving back from disneyland ♪ ♪ going over all the fun ♪ ♪ what was best space mountain ♪ ♪ or getting wet on the grizzly river run yeah ♪ ♪ greatest time of our kids life ♪ ♪ what a magical moment for me and my wife ♪ ♪ then i miss our exit ♪ ♪ and i scream fucking cunt ♪ ♪ and its like disneyland never happened ♪thats a mistake and my kids uh the fucking best time of your life with your kids right dont you love your kids more than anything i remember when my daughter was born ill never forget what my father said my father said youre gonna drop the baby thats going to happen i go oh okay he goes that shit happens thats life you drop the baby fuck it but you pick the baby up and you dont fucking make a big fuss because the babys gonna be like what the fuck that wasnt supposed to happen you play it off like thats life you pick the baby up look at it you go whats up youre alright okay i guess dad no no thats life you drop the baby what are you gonna do youre busy you got the fucking groceries in your hand you got you got the baby drop the baby you got the groceries you look down put the baby on your foot you fuckin kick it up catch the baby you keep going you look at the baby hey how you doing man everything good the babys like i guess yeah thats life you know hes like i fucking dropped your little brother fucking times i go i got a little brother he goes you didbut uh my father my father used to always go for the belt hed be like youre gonna get the belt fucking i dont do that with my kids just cause i wear sweatpants im like youre gonna get the tassels daddy gonna daddy gonna get you i went to the daddy i went to the daddydaughter dance recently she didnt fucking show son of a bitch standing there with a corsageheartbroken by the way if this could work it would be great honestly would it can it workno not to be a dick if i knew it was gonna take this long obviously id have waited – youre doing a good jobyou sound snippy though dont you sound a little snippy for a guy who fucked me this hard were working on it dont worry about italright ♪ sleep in late ♪ ♪ eat a big breakfast ♪ ♪ walk the dog ♪ ♪ watch the news ♪ ♪ go to the bathroom ♪ ♪ start my laundry ♪ ♪ go on the internet ♪ ♪ buy some new shoes ♪ ♪ leave the apartment for lunch with my landlord ♪ ♪ come back home ♪ ♪ take the dog for a walk again ♪ ♪ turn on my tv ♪ ♪ watch jerry maguire ♪ ♪ ive seen it before ♪ ♪ but ill watch it again ♪ ♪ pretty good day ♪ ♪ pretty good life ♪ ♪ i am clinically depressed ♪alright sorry so uh im sorry that was ehh so im at the fucking airport ever have a guy say to you hey can you watch my bag while i go to the bathroom and youre like what this guys like watch my bag when i go to the bathroo

In [29]:
# Playing around with CountVectorizer 

cv2 = CountVectorizer(ngram_range = (1, 2), min_df = 2, max_df = 0.9, stop_words = 'english')

data_cv = cv2.fit_transform(data_clean.transcript)
data_dtm = pd.DataFrame(data_cv.toarray(), columns=cv2.get_feature_names_out())
data_dtm.index = data_clean.index
data_dtm

,ability,able,abortion,absolutely,absurd,absurdities,absurdities modern,absurdities sharp,absurdity,abuse,...,youve seen,youve south,youwhat,youyou,yummy,ze,zero,zombie,zoom,éclair
adam,0,0,0,2,0,1,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
ali,0,2,0,0,0,1,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
anthony,0,0,2,0,0,1,0,1,0,0,...,2,0,0,0,0,0,0,0,0,0
bill,0,1,0,3,0,1,0,1,0,0,...,0,0,0,0,1,1,1,1,0,0
bo,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
dave,0,0,0,0,0,1,0,1,0,0,...,1,1,0,0,0,0,0,0,0,0
dylan,1,0,0,0,1,3,0,1,0,0,...,0,0,1,0,0,0,0,0,0,2
hasan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
jamie,0,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
jim,0,1,0,0,0,1,0,1,0,0,...,1,1,0,0,0,0,0,0,0,0
joe,0,2,0,0,0,1,0,1,0,1,...,2,0,0,0,0,0,0,0,0,0
john,0,3,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
kelsey,0,3,0,2,0,2,1,1,0,0,...,0,0,0,0,0,0,1,0,1,0
kevin,0,0,0,1,0,2,1,1,1,0,...,0,0,0,0,0,0,3,0,0,0
louis,0,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,2,0,0,0
mike,0,0,0,0,0,1,0,1,0,0,...,1,0,0,0,0,0,1,0,0,0
ramy,0,1,1,1,0,1,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
ricky,2,2,0,0,0,1,0,1,0,0,...,0,0,1,0,1,0,0,0,0,0
sal,0,2,0,0,1,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
seth,0,0,0,0,0,1,0,1,1,0,...,0,0,0,0,0,2,0,0,0,0